### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by auticons0902** [SU-ECE-18-7/hotspotter#5]
[aq] beginning autoquery

====================
[hs] query database
====================
[mc3] FEAT_UID is different. Need to reload features
[mc3] Old: None
[mc3] New: _FEAT(hesaff+sift,0_9001)_CHIP(sz750)
[hs] unload_cxdata(cx='all')
[hs] Unloading all data
[hs] finished unloading all data

=============================
[cc2] Precomputing chips and loading chip paths: 'db_multi_cats'
=============================
[cc2] chip_uid = '_CHIP(sz750)'
[parallel] Already computed 71 compute_chip tasks
[parallel] ... No compute_chip tasks left to compute!
[cc2] Done Precomputing chips and loading chip paths
[cc2]=============================

=============================
[fc2] Precomputing and loading features: 'db_multi_cats'
=============================
[fc2] feat_uid = '_FEAT(hesaff+sift,0_9001)_CHIP(sz750)'
[fc2]  Loaded kpts_list and desc_list from big cache
[fc2]=============================
[mc3] query_dcxs(): query_uid = '_NN(K4+1,last,cks1024)_FILT(lnbnn_0.01)_SV(1000,0.01,0.5_2,csum)_AGG(vsmany,csum)' 
[mc3] Execute query: qcids=[1]
[res] res.load() fpath='res_w1=@2,y0es`5;[=]_qcid=1.npz'
[mc3] ... query result cache hit
QueryResult
    dict filt2_meta = 
        {
          lnbnn : [[   4   24    4]
         [  50  325    4]
         [  30   34    4]
         ..., 
         [  37 1055    4]
         [  66  925    4]
         [  44  261    4]]
        }
    
    float32 cx2_score = { shape:[71] mM:(0.0, 79872.906) }
    int qcx = 0
    object cx2_fk = { shape:[71] mM:NA }
    object cx2_fm = { shape:[71] mM:NA }
    object cx2_fs = { shape:[71] mM:NA }
    str query_uid = '_NN(K4+1,last,cks1024)_FILT(lnbnn_0.01)_SV(1000,0.01,0.5_2,csum)_AGG(vsmany,csum)_FEAT(hesaff+sift,0_9001)_CHIP(sz750)'
    |S118 title = { shape:[] mM:NA }
    |S118 uid = { shape:[] mM:NA }
    |S137 true_uid = { shape:[] mM:NA }
    
1  ==  1
Block wrapper caugt exception in 'autoquery'
back = <hsgui.guiback.MainWindowBackend object at 0x7fbb31c9a050>
Traceback (most recent call last):
  File "/home/auticons/code/hotspotter/hsgui/guitools.py", line 107, in block_wrapper
    result = func(back, *args, **kwargs)
  File "/home/auticons/code/hotspotter/hsgui/guiback.py", line 785, in autoquery
    back.hs.autoquery()
  File "/home/auticons/code/hotspotter/hotspotter/HotSpotterAPI.py", line 490, in autoquery
    scoreMat = aq.makeScoreMat(hs)         # Autoquery (make score matrix)
  File "/home/auticons/code/hotspotter/hotspotter/autoquery.py", line 60, in makeScoreMat
    elif sameSet(c1_gname, c2_gname, params.maximum_time_delta) and scoreMat[i][j] == 0.0:
  File "/home/auticons/code/hotspotter/hotspotter/autoquery.py", line 93, in sameSet
    if getLoc(chip1) == getLoc(chip2):
  File "/home/auticons/code/hotspotter/hotspotter/autoquery.py", line 120, in getLoc
    loc = (chipList[0] + "__" + chipList[1] +"__"+chipList[2])
IndexError: list index out of range

Traceback (most recent call last):
  File "/home/auticons/code/hotspotter/hsgui/guitools.py", line 85, in slot_wrapper
    result = func(self, *args, **kwargs)
  File "/home/auticons/code/hotspotter/hsgui/guitools.py", line 107, in block_wrapper
    result = func(back, *args, **kwargs)
  File "/home/auticons/code/hotspotter/hsgui/guiback.py", line 785, in autoquery
    back.hs.autoquery()
  File "/home/auticons/code/hotspotter/hotspotter/HotSpotterAPI.py", line 490, in autoquery
    scoreMat = aq.makeScoreMat(hs)         # Autoquery (make score matrix)
  File "/home/auticons/code/hotspotter/hotspotter/autoquery.py", line 60, in makeScoreMat
    elif sameSet(c1_gname, c2_gname, params.maximum_time_delta) and scoreMat[i][j] == 0.0:
  File "/home/auticons/code/hotspotter/hotspotter/autoquery.py", line 93, in sameSet
    if getLoc(chip1) == getLoc(chip2):
  File "/home/auticons/code/hotspotter/hotspotter/autoquery.py", line 120, in getLoc
    loc = (chipList[0] + "__" + chipList[1] +"__"+chipList[2])
IndexError: list index out of range

**Comment by auticons0902** [comment]
Solved
